[package]
name = "basic-http-server"
version = "0.4.3"
authors = ["Brian Anderson <banderson@mozilla.com>"]
license = "MIT/Apache-2.0"
description = "A basic HTTP file server"
homepage = "https://github.com/brson/basic-http-server"
repository = "https://github.com/brson/basic-http-server"
edition = "2018"

[dependencies]
futures = "0.1.14"
hyper = "0.12.22"
http = "0.1.15"
mime = "0.3.13"
clap = "2.25.0"
tokio = "0.1.17"
threadpool = "1.4.0"
net2 = "0.2"
libc = "0.2.4"
error-type = "0.1.2"
handlebars = "2.0.0-beta.2"
serde = "1.0.90"
serde_derive = "1.0.90"
